TPN1EnWeb.Web/Areas/Admin/Controllers/BrandController.cs
using AutoMapper;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Mono.TextTemplating;
using TPN1EnWeb.Entidades;
using TPN1EnWeb.Entidades.ViewModels;
using TPN1EnWeb.Servicios.Interfaces;
using TPN1EnWeb.Servicios.Servicios;
using X.PagedList;
using X.PagedList.Extensions;

namespace TPN1EnWeb.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class BrandController : Controller
    {
        private readonly IBrandService? _brandService; //Le pido los datos al Servicio
        private readonly IMapper? mapper;
        private readonly IShoeService? _shoeService;
        private readonly IWebHostEnvironment? _webHostEnvironment;

        public BrandController(IBrandService? brandService, IMapper? _mapper, IShoeService? shoeService, IWebHostEnvironment? webHostEnvironment)
        {
            _brandService = brandService;
            mapper = _mapper;
            _shoeService = shoeService;
            _webHostEnvironment = webHostEnvironment;//TRAE IFORMACIÓN DE MIS CARPETAS EN MI SERVIDOR, en este caso la vamos usar para la carpeta images en wwwroot
        }

        public IActionResult Index(int? page, string? searchTerm = null, int pageSize = 10, bool viewAll = false) //Muestro todas las Brand
        {
            int pagenumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            ViewBag.currentsearchTerm = searchTerm; //Un viewBag es como una variable de la vista que se usa en la vista para no ensuciar más el modelo de mi vista
            IEnumerable<Brand> brands;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    brands = _brandService!.GetBrands(orderBy: o => o.OrderBy(b => b.BrandName), filter: f => f.BrandName.Contains(searchTerm!))!;
                }
                else
                {
                    brands = _brandService!.GetBrands(orderBy: o => o.OrderBy(b => b.BrandName))!;
                }
            }
            else
            {
                searchTerm = string.Empty;
                ViewBag.currentsearchTerm = searchTerm;
                brands = _brandService!.GetBrands(orderBy: o => o.OrderBy(b => b.BrandName))!;

            }
            var listabrandvm = new List<BrandListVM>();
            foreach (var brand in brands)
            {
                var brandVm = new BrandListVM()
                {
                    BrandId = brand.BrandId,
                    BrandName = brand.BrandName,
                    ShoeCount = _shoeService!.GetCantidad(s => s.BrandId == brand.BrandId)
                };
                listabrandvm.Add(brandVm);
            }
            PagedList<BrandListVM> listaVm = new PagedList<BrandListVM>(listabrandvm, pagenumber, pageSize);
            listaVm.ToPagedList(pagenumber, pageSize);
            return View(listaVm);
        }
        public IActionResult UpSert(int? id, string? returnurl = null)
        {
            BrandEditVM? brandEditVM;
            if (id is null || id.Value == 0)
            {
                brandEditVM = new BrandEditVM();
            }
            else
            {
                try
                {
                    string? wwwWebRoot = _webHostEnvironment!.WebRootPath;
                    Brand? brand = _brandService?.GetBrand(filter: brand => brand.BrandId == id);
                    if (brand == null)
                    {
                        return NotFound();
                    }
                    if (!string.IsNullOrEmpty(brand.imageURL))
                    {
                        string filePath = Path.Combine(wwwWebRoot, brand.imageURL.TrimStart('/'));
                        ViewData["fileExist"] = System.IO.File.Exists(filePath);
                    }
                    else
                    {
                        ViewData["fileExist"] = false;
                    }
                    brandEditVM = mapper?.Map<BrandEditVM>(brand);
                    brandEditVM!.ReturnUrl = returnurl;

                }
                catch (Exception)
                {

                    throw;
                }           
            }
            return View(brandEditVM);
        }
        [HttpPost]
        public IActionResult UpSert(BrandEditVM? brandEditVM)
        {
            string? returnurl=brandEditVM!.ReturnUrl;

            if (!ModelState.IsValid)
            {
                return View(brandEditVM);
            }
            try
            {
                string? webroot = _webHostEnvironment!.WebRootPath;
                Brand? brand = mapper?.Map<Brand>(brandEditVM);
                if (brand == null)
                {
                    ModelState.AddModelError(string.Empty, "No Brand has been supplied");
                    return View(brandEditVM);
                }

                if (_brandService?.Existe(brand) ?? true)
                {
                    ModelState.AddModelError(string.Empty, "Registro Duplicado¡¡¡¡");
                    return View(brandEditVM);
                }
                if (brandEditVM!.ImageFile != null)
                {
                    var permittedExtensions = new string[] { ".jpg", ".jpeg", ".gif", ".png" }; //Estas van a ser las extesiones que voy a permitir subir, si no hay alguna que yo desee, la agrego
                    string fileExtension = Path.GetExtension(brandEditVM.ImageFile.FileName); //Obtenemos la extension del nombre de nuestro archivo
                    if (!permittedExtensions.Contains(fileExtension)) // si la extension que obtuvimos de nuestro archivo no esta en los permitidos, va a tirar error y volver a la vista
                    {
                        ModelState.AddModelError(string.Empty, "File not allowed");
                        return View(brandEditVM);
                    }

                    if (brandEditVM.imageURL != null)
                    {
                        string? oldPath = Path.Combine(webroot, brand.imageURL!.TrimStart('/'));
                        if (System.IO.File.Exists(oldPath)) //Me fijo si existe esta ruta
                        {
                            System.IO.File.Delete(oldPath);//La doy de baja porque voy a ingresar una nueva en el objeto
                        }
                    }
                    string fileName = $"{Guid.NewGuid()}{Path.GetExtension(brandEditVM.ImageFile.FileName)}";
                    string pathName = Path.Combine(webroot, "images", fileName); //Nombre de la ruta combinando el webroot que es la ruta web,el nombre del archivo y el string "images"
                    using (var filestream = new FileStream(pathName, FileMode.Create))
                    {
                        brandEditVM.ImageFile.CopyTo(filestream); // Con esto subo mi imagen a la carpeta images en wwroot
                    }
                    brand.imageURL = $"/images/{fileName}";
                }
                _brandService.Guardar(brand);
                TempData["success"] = "Record added/edited successfully";
                return !string.IsNullOrEmpty(returnurl)
            ? Redirect(returnurl)
            : RedirectToAction("Index"); //Tuve que escribirlo así para que me desaparesca el error de que todas las rutas deben tener un retorno
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while editing the record.");
                return View(brandEditVM);
            }
        }
        [HttpDelete]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Brand? brand = _brandService?.GetBrand(filter: brand => brand.BrandId == id);
            if (brand is null)
            {
                return NotFound();
            }
            if (_brandService?.EstaRelacionado(brand) ?? true)
            {
                return Json(new
                {
                    success = false,
                    message = "Related Record..."
                });
            }
            //PREGUNTAR, POR QUÉ ES NECESARIO BORRAR LA RUTA SI YA LA DEBERÍA BORRAR CON EL OBJETO?
            if (brand.imageURL != null)
            {
                string? webroot = _webHostEnvironment!.WebRootPath;
                string? oldPath = Path.Combine(webroot, brand.imageURL!.TrimStart('/'));
                if (System.IO.File.Exists(oldPath)) //Me fijo si existe esta ruta
                {
                    System.IO.File.Delete(oldPath);//La doy de baja porque voy a ingresar una nueva en el objeto
                }
            }
            _brandService?.Borrar(brand);
            return Json(new { success = true, message = "Record deleted successfully" });
        }

        public IActionResult Details(int? id)
        {
            Brand brand = _brandService?.GetBrand(filter: filter => filter.BrandId == id)!;
            if (brand is null)
            {
                return NotFound();
            }
            IEnumerable<Shoe> listaShoeFiltradaPorBrand;
            listaShoeFiltradaPorBrand = _shoeService?.GetShoes(filter: filter => filter.BrandId == id, propertiesNames: "Genres,Color,Sports,Brands")!;
            var listavm = mapper?.Map<IEnumerable<ShoeListVM>>(listaShoeFiltradaPorBrand).ToList();
            return View(listavm);
        }
    }
}

TPN1EnWeb.Web/Areas/Admin/Views/Brand/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Brand
@{
    ViewData["Title"] = "Delete Brand";
}
<form method="post" asp-controller="Brand" asp-action="Delete">
    @*CUANDO COPIES Y PEGUES ACORDATE DE CAMBIAR LAS ACCIONES Y LOS CONTROLADORES*@
    <input type="hidden" asp-for="BrandId" />@*IMPORTANTE ESTE CAMPO CUANDO EDITO O BORRO
    ya que acá se guarda el ID de mi objeto, si yo no pongo este campo en vez de editar va a guardar en este caso o en vez de borrar
    lo que va a pasar es que no pueda encontrar el objeto porque el ID va a ser 0
    *@

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Delete Brand</h2>
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="BrandName"></label>@*Esto es como el titulo de nuestro input para agregar datos*@
        <input asp-for="BrandName" disabled type="text" class="form-control" />@*Esto es para ingresar el Colour nuevo*@
    </div>
    <button class="btn btn-danger">
        <i class="bi bi-save"></i>
        Confirm
    </button>
    <a asp-controller="Brand" asp-action="Index" class="btn btn-info">
        @*Conesto indico con que controlador manejar y que acción realizar
        en este caso es regresar a la lista*@
        <i class="bi bi-arrow-return-left"></i>
        Back to List
    </a>
</form>

TPN1EnWeb.Web/Areas/Admin/Views/Brand/Details.cshtml
@model IEnumerable<ShoeListVM>
@{
    ViewData["Title"] = "List of Shoes";
}
<div class="row w-60 mb-3">
    <div class="col-8">
        <h1 style="color:white">
            Shoes with this Brand:   @{
                foreach (var item in Model)
                {
                    @item.brand
                    break;
                }
            }
        </h1>
    </div>
</div>

<table class="table table-dark table-hover w-auto">
    <thead class="border-2">
        <tr bordercolor="dark">
            <th colspan="8" valign="middle" align="center">Shoe</th>
        </tr>
        <tr>
            <th>Colour</th>
            <th>Genre</th>
            <th>Sport</th>
            <th>Model</th>
            <th>Price</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr id="@item.shoeId">
                    <td>@Html.Raw(@item.color)</td>
                    <td>@Html.Raw(@item.genre)</td>
                    <td>@Html.Raw(@item.sport)</td>
                    <td>@Html.Raw(@item.model)</td>
                    <td>@Html.Raw(@item.price)</td>
                    <td>@Html.Raw(@item.descripcion)</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>No hay datos en la lista</td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="Brand" asp-action="Index" class="btn btn-info">
    <i class="bi bi-arrow-return-left"></i>
    Back to List
</a>

TPN1EnWeb.Web/Areas/Admin/Views/Brand/Index.cshtml
@using X.PagedList
@using X.Web.PagedList
@model IPagedList<BrandListVM>;//Con esto le indico el tipo de modelo que va a recibir esta vista, le pasó este tipo porque en el controlador le paso un parametro de tipo
@{
    ViewData["Title"] = "List of Brands";
}

<div class="row w-60 mb-3">
    @Html.AntiForgeryToken()
    <div class="col-5">
        <h1 style="color:#ffffff">List of Brands</h1>
    </div>
</div>
    <form method="get" class="form-inline" asp-action="Index" style="padding-bottom:5px">
        <div class="d-flex flex-row align-items-center">
        <div class="col-auto mx-1" style="color:#ffffff">
                <label for="pageSize">Show:</label>
            </div>
            <div class="col-auto mx-2">
               <partial name="_selectPageSize" model="ViewBag.currentPageSize" />
            </div>
            <div class="col-auto mx-2" style="width: 200px;">
                <input type="text" name="searchTerm" id="searchTerm" class="form-control" placeholder="Search by..." value="@ViewBag.currentSearchTerm" />
            </div>
            <div class="col-auto d-flex">
                <button type="submit" class="btn btn-primary mx-2">
                    <i class="bi bi-search"></i> Search
                </button>
                <button type="submit" class="btn btn-secondary" id="viewAll" name="viewAll" value="true">
                    <i class="bi bi-list"></i> View All
                </button>
            </div>
        <div class="col-7 mx-2">
            <a asp-controller="Brand" asp-action="UpSert" class="btn btn-dark">
                <i class="bi bi-node-plus-fill"></i>
                New
            </a>
        </div>
        </div>
    </form>
<table class="table table-dark table-hover w-75 ">
    <thead>
        <tr>
            <th>Brand</th>
            <th class ="text-align text-center">Countity of Shoes by Brand</th>
            <th>Active</th> 
            <th>Accions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr id="@item.BrandId">
                    <td>@Html.Raw(@item.BrandName)</td>
                    <td class="text-align text-center">@item.ShoeCount</td>
                    <td>
                    @if (item.Active)
                    {
                        <span class="badge text-bg-primary">Yes</span>
                    }
                    else
                    {
                        <span class="badge text-bg-warning">No</span>
                    }
                    </td>
                    <td>

                        <a onclick="Delete('/Admin/Brand/Delete/@item.BrandId',@item.BrandId,'@item.BrandName')" class="btn btn-danger"> @*Poner la barra adelante de admin*@
                            <i class="bi bi-trash"></i>
                            Delete
                        </a>

                        <a asp-area="Admin" asp-controller="Brand" asp-action="UpSert" asp-route-id="@item.BrandId"asp-route-returnurl="@(Context.Request.Path+Context.Request.QueryString)"class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                            Edit
                        </a>
                        <a asp-controller="Brand" asp-action="Details" asp-route-id="@item.BrandId" class="btn btn-info" style="background-color:chartreuse">
                            Details
                        </a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>No hay datos en la lista</td>
                <td></td>
                <td></td>
            </tr>
        }
    </tbody>
</table>
<partial name="_Pager" model="@Model" />

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/common.js"></script>
}

TPN1EnWeb.Web/Areas/Admin/Views/Brand/UpSert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model BrandEditVM
@{
    ViewData["Title"] = "Agregar Brand";
    bool filExist = false;
    if (ViewData["fileExist"] != null)
    {
        filExist = (bool)ViewData["fileExist"]!;
    }
}
<form method="post" asp-controller="Brand" asp-action="UpSert" enctype="multipart/form-data">
    <input type="hidden" asp-for="BrandId" /> @*Guardo en un input escondido el id del objeto para poder editarlo*@
    <input type="hidden" asp-for="imageURL" />@* Guardo la ruta de la imagen en caso de que edite el objeto y no la imagen y que la ruta de esa imagen no se borre*@
    <input type="hidden" asp-for="ReturnUrl" />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> @(Model.BrandId==0? "Agregar Brand":"Edit Brand")</h2>
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div> @*Este span es para que me muestre el mensaje de "registro duplicado"*@
    </div>
    <div class=" row">
        <div class="mb-3 col-auto">
            <label asp-for="BrandName"></label>
            <input asp-for="BrandName" class="form-control" />
            <span asp-validation-for="BrandName" class="text-danger"></span> @*Este span es para que me muestre el mensaje de "Debe ingresar un registro"*@
        </div>
        <div class="form-group py2 mb-3 col-auto">
            <label class="form-label" asp-for="imageURL"></label>
            <input type="file" class="form-control" asp-for="ImageFile" />
        </div>
        @if (Model.imageURL!=null)
        {
            if (filExist)
            { 
                <div class="col-auto text-center mt-3">
                    <img src="@Model.imageURL" style="width:200px; height:150px; border:dashed 1px" />
                </div>
            }
            else
            {
                <div class="col-auto text-center mt-3">
                    <img src="~/images/8499cb70-aaa3-4fd9-b516-a00b2920f131.jpg" style="width:200px; height:150px; border:dashed 1px" />
                </div>
            }
        }
        else
        {
            <div class="col-auto text-center mt-3">
                <img src="~/images/8499cb70-aaa3-4fd9-b516-a00b2920f131.jpg" style="width:200px; height:150px; border:dashed 1px" />
            </div>
        }
        
    </div>
    
    @if (Model.BrandId == 0)
    {
        <button type="submit" class="btn btn-success">
            <i class="bi bi-save"></i>
            Confirm
        </button>
    }
    else
    {
        <button type="submit" class="btn btn-warning">
            <i class="bi bi-save"></i>
            Confirm
        </button>
    }
    <a asp-controller="Brand" asp-action="Index" class="btn btn-info"> 
        <i class="bi bi-arrow-return-left"></i>
        Back to List
    </a>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}