TPN1EnWeb.Web/Areas/Admin/Controllers/ApplicationUsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TPN1EnWeb.Entidades;
using TPN1EnWeb.Entidades.ViewModels;
using TPN1EnWeb.Servicios.Interfaces;
using X.PagedList.Extensions;

namespace TPN1EnWeb.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ApplicationUsersController : Controller
    {

        private readonly IApplicationUsersService? _usersService;
        private readonly IMapper? _mapper;

        public ApplicationUsersController(IApplicationUsersService? usersService,
            IMapper mapper)
        {
            _usersService = usersService ?? throw new ApplicationException("Dependencies not set");
            _mapper = mapper ?? throw new ApplicationException("Dependencies not set"); ;
        }

        public IActionResult Index(int? page, string? searchTerm = null, bool viewAll = false, int pageSize = 10)
        {
            int pageNumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            IEnumerable<ApplicationUser>? users;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    users = _usersService?
                        .GetAll(orderBy: o => o.OrderBy(c => c.LastName).ThenBy(c => c.FirstName),
                            filter: c => c.FirstName.Contains(searchTerm)
                            || c.LastName!.Contains(searchTerm),
                            propertiesNames: "Country,State,City");
                    ViewBag.currentSearchTerm = searchTerm;
                }
                else
                {
                    users = _usersService?
                            .GetAll(orderBy: o => o.OrderBy(c => c.LastName).ThenBy(c => c.FirstName),
                        propertiesNames: "Country,State,City");
                }
            }
            else
            {
                users = _usersService?
                        .GetAll(orderBy: o => o.OrderBy(c => c.LastName).ThenBy(c => c.FirstName),
                        propertiesNames: "Country,State,City");
            }

            var usersVm = _mapper?.Map<List<ApplicationUserListVm>>(users)
                    .ToPagedList(pageNumber, pageSize);
            return View(usersVm);
        }
        public IActionResult Details(string id)
        {
            var applicationUser = _usersService!.Get(filter: o => o.Id == id,
                propertiesNames: "Country,State,City,OrderHeaders");
            return View(applicationUser);
        }
    }
}

TPN1EnWeb.Web/Areas/Customer/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TPN1EnWeb.Servicios.Interfaces;

namespace TPN1EnWeb.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = "Customer, Admin")]
    public class OrdersController : Controller
    {
        private readonly IOrderHeadersService? _headersService;
        private readonly IShoeSizeService _shoeSizeService;
        private readonly IMapper? _mapper;

        public OrdersController(IOrderHeadersService? headersService,
            IShoeSizeService shoeSizeService,
            IMapper? mapper)
        {
            _headersService = headersService;
            _shoeSizeService = shoeSizeService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var orderHeader = _headersService!.Get(filter: o => o.OrderHeaderId == id,
                propertiesNames: "OrderDetail");
            foreach (var detail in orderHeader!.OrderDetail)
            {
                var shoesizeInDetail = _shoeSizeService.GetShoeSize(filter: p => p.ShoeSizeId == detail.ShoeSizeId, propertiesNames:"Shoe,Size");
                detail.ShoeSizes = shoesizeInDetail;
            }
            return View(orderHeader);
        }
        #region API CALLS
        [HttpGet]
        public JsonResult GetAll() 
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity!;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var orderList = _headersService!.GetAll(filter:
                o => o.ApplicationUserId == claims!.Value);
            return Json(new { data = orderList });
        }
        #endregion
    }
}

TPN1EnWeb.Web/Areas/Customer/Views/Orders/Details.cshtml
@using TPN1EnWeb.Utilities
﻿
@model OrderHeader
@{
    string formatDate(DateTime date)
    {
        return date.ToShortDateString();
    }
}
<div style="color:#ffffff">
    <h4>Orders Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label>Order No."</label>
        </dt>
        <dd class="col-sm-4">
            <input asp-for="OrderHeaderId" class="form-control form-control-sm" readonly />
        </dd>
        <dt class="col-sm-2">
            <label >Order Date</label>
        </dt>
        <dd class="col-sm-4">
            <input type="text" value="@formatDate(Model.OrderDate)" class="form-control form-control-sm" readonly />
        </dd>
        <dt class="col-sm-2">
            <label >Shipping Date</label>
        </dt>
        <dd class="col-sm-4">
            <input type="text" value="@formatDate(Model.ShippingDate)" class="form-control form-control-sm" readonly />
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole(WC.Role_Admin))
    {
        <a asp-area="Admin" asp-controller="ApplicationUsers" asp-action="Details" asp-route-id="@Model.ApplicationUserId" class="btn btn-success btn-sm">
            <i class="bi bi-backspace"></i>&nbsp;
            Back to List
        </a>

    }
    else
    {
        <a asp-action="Index" class="btn btn-success btn-sm">
            <i class="bi bi-backspace"></i>&nbsp;
            Back to List
        </a>

    }
</div>
<table class="table table-bordered table-hover mt-3" style="color:#ffffff">
    <thead>
        <tr>
            <th style="width:20%">Description</th>
            <th style="width:10%">Model</th>
            <th style="width:10%">Size</th>
            <th style="width:20%">Unit Price</th>
            <th style="width:15%">Quantity</th>
            <th style="width:20%">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderDetail)
        {
            <tr>
                <td>
                    @item.ShoeSizes!.Shoe.Descripcion
                </td>
                <td>
                    @item.ShoeSizes!.Shoe.Model
                </td>
                <td>
                    @item.ShoeSizes!.Size.SizeNumber
                </td>
                <td class="text-end">
                    @item.Price.ToString("C",System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))
                </td>
                <td class="text-end">
                    @item.Quantity
                </td>
                <td class="text-end" >
                    @((item.Price * item.Quantity).ToString("C",System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))
                </td>

            </tr>
        }
        <tr>
            <td class="fw-bold" colspan="5">
                Total:
            </td>
            <td class="text-end fw-bold">
                @Model.OrderTotal.ToString("C",System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))
            </td>
        </tr>
    </tbody>
</table>

TPN1EnWeb.Web/Areas/Customer/Views/Orders/Index.cshtml
<div class="container">
    @Html.AntiForgeryToken()
    <div class="row mb-3" style="color:#ffffff">
        <div class="col-6">
            <h3>Order's List</h3>

        </div>
   </div>
    <table id="orderTable" class="table table-bordered table-hover" style="color:#ffffff">
        <thead>
            <tr>
                <th style="width:10%">Order No.</th>
                <th style="width:15%">Order Date</th>
                <th style="width:15%">Shipping Date</th>
                <th style="width:10%">Order Total</th>
                <th style="width:15%">Actions</th>

            </tr>
        </thead>
    </table>


</div>
@section Scripts {
    <script src="~/js/order.js"></script>
}