TPN1EnWeb.Web/Areas/Admin/Controllers/ShoeController.cs
using AutoMapper;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Composition;
using System.Drawing.Drawing2D;
using System.Drawing;
using TPN1EnWeb.Entidades;
using TPN1EnWeb.Entidades.ViewModels;
using TPN1EnWeb.Servicios.Interfaces;
using TPN1EnWeb.Servicios.Servicios;
using X.PagedList;
using X.PagedList.Extensions;
using Size = TPN1EnWeb.Entidades.Size;
using System.Security.Policy;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace TPN1EnWeb.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ShoeController : Controller
    {
        private readonly IShoeService? _shoeService;
        private readonly IBrandService? _brandService;
        private readonly IColorService? _colorService;
        private readonly IGenreService? _genreService;
        private readonly ISportService? _sportService;
        private readonly ISizeService? _sizeService;
        private readonly IShoeSizeService? _shoeSizeService;
        private readonly IMapper? _mapper;
        private readonly IWebHostEnvironment? _webHostEnvironment;

        public ShoeController(IShoeService? shoeService, IMapper? mapper, IBrandService? brandService, IColorService? colorService, IGenreService? genreService, ISportService? sportService, ISizeService? sizeService, IShoeSizeService? shoeSizeService, IWebHostEnvironment? webHostEnvironment)
        {
            _shoeService = shoeService;
            _mapper = mapper;
            _brandService = brandService;
            _colorService = colorService;
            _genreService = genreService;
            _sportService = sportService;
            _sizeService = sizeService;
            _shoeSizeService = shoeSizeService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(int? page, string? searchTerm = null, int? FilterBrandId = null, int? FilterColorId = null, int? FilterGenreId = null, int? FilterSportId = null, int pageSize = 10, bool viewAll = false, string orderBY = "Brand")
        {
            int pagenumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            ViewBag.currentsearchTerm = searchTerm; //Un viewBag es como una variable de la vista que se usa en la vista para no ensuciar más el modelo de mi vista
            ViewBag.currentFilterBrandId = FilterBrandId;
            ViewBag.currentFilterColorId = FilterColorId;
            ViewBag.currentFilterGenreId = FilterGenreId;
            ViewBag.currentFilterSportId = FilterSportId;
            ViewBag.currentOrderBy = orderBY;
            IEnumerable<Shoe> shoes;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm) || FilterBrandId != null || FilterColorId != null || FilterGenreId != null || FilterSportId != null)
                {
                    if (searchTerm != null && FilterBrandId == null && FilterColorId == null && FilterGenreId == null && FilterSportId == null)
                    {
                        FilterBrandId = null;
                        FilterColorId = null;
                        FilterGenreId = null;
                        FilterSportId = null;
                        ViewBag.currentFilterBrandId = FilterBrandId;
                        ViewBag.currentFilterColorId = FilterColorId;
                        ViewBag.currentFilterGenreId = FilterGenreId;
                        ViewBag.currentFilterSportId = FilterSportId;
                        //Hay que escribir las propiedades como estan en la entidad
                        shoes = _shoeService!.GetShoes(propertiesNames: "Sports,Brands,Color,Genres", orderBy: o => o.OrderBy(c => c.Price),
                                    filter: f => f.Brands!.BrandName.Contains(searchTerm!) || f.Color!.ColorName.Contains(searchTerm) || f.Sports!.SportName.Contains(searchTerm) ||
                                    f.Genres!.GenreName.Contains(searchTerm))!;
                    }
                    else
                    {
                        searchTerm = string.Empty;
                        ViewBag.currentsearchTerm = searchTerm;
                        shoes = _shoeService!.GetShoes(propertiesNames: "Sports,Brands,Color,Genres", orderBy: o => o.OrderBy(order => order.Price),
                            filter: f => f.BrandId == FilterBrandId || f.ColourId == FilterColorId || f.GenreId == FilterGenreId || f.SportId == FilterSportId)!;
                    }

                }
                else
                {
                    shoes = _shoeService!.GetShoes(orderBy: o => o.OrderBy(b => b.Price), propertiesNames: "Sports,Brands,Color,Genres")!;
                }
            }
            else
            {
                searchTerm = string.Empty;
                FilterBrandId = null;
                FilterColorId = null;
                FilterGenreId = null;
                FilterSportId = null;
                ViewBag.currentsearchTerm = searchTerm;
                ViewBag.currentFilterBrandId = FilterBrandId;
                ViewBag.currentFilterColorId = FilterColorId;
                ViewBag.currentFilterGenreId = FilterGenreId;
                ViewBag.currentFilterSportId = FilterSportId;
                shoes = _shoeService!.GetShoes(orderBy: o => o.OrderBy(b => b.Price), propertiesNames: "Sports,Brands,Color,Genres")!;
            }

            var listavm = _mapper?.Map<IEnumerable<ShoeListVM>>(shoes).ToList();
            if (orderBY == "Brand")
            {
                listavm = listavm!.OrderBy(o => o.brand).ToList();
            }
            if (orderBY == "Colour")
            {
                listavm = listavm!.OrderBy(o => o.color).ToList();
            }
            if (orderBY == "Genre")
            {
                listavm = listavm!.OrderBy(o => o.genre).ToList();
            }
            if (orderBY == "Sport")
            {
                listavm = listavm!.OrderBy(o => o.sport).ToList();
            }
            var shoeFilterVM = new ShoeFilterVm()
            {
                Shoes = listavm!.ToPagedList(pagenumber, pageSize),
                Brands = _brandService!.GetBrands(orderBy: o => o.OrderBy(order => order.BrandName))!.Select(s => new SelectListItem { Text = s.BrandName, Value = s.BrandId.ToString() }).ToList(),
                Genres = _genreService!.GetGenres(orderBy: o => o.OrderBy(order => order.GenreName))!.Select(s => new SelectListItem { Text = s.GenreName, Value = s.GenreId.ToString() }).ToList(),
                Colors = _colorService!.GetColours(orderBy: o => o.OrderBy(order => order.ColorName))!.Select(s => new SelectListItem { Text = s.ColorName, Value = s.ColourId.ToString() }).ToList(),
                Sports = _sportService!.GetSports(orderBy: o => o.OrderBy(order => order.SportName))!.Select(s => new SelectListItem { Text = s.SportName, Value = s.SportId.ToString() }).ToList(),

            };
            return View(shoeFilterVM);
        }
        public IActionResult UpSert(int? id, string? returnurl = null)
        {
            ShoeEditVM? shoeEditVM;
            if (id is null || id.Value == 0)
            {
                shoeEditVM = new ShoeEditVM();
                RercargarCombos(shoeEditVM);
            }
            else
            {
                try
                {
                    string? wwwWebRoot = _webHostEnvironment!.WebRootPath;
                    Shoe? shoe = _shoeService?.GetShoe(s => s.ShoeId == id.Value);
                    if (shoe == null)
                    {
                        return NotFound();
                    }
                    if (!string.IsNullOrEmpty(shoe.imageURL))
                    {
                        string filePath = Path.Combine(wwwWebRoot, shoe.imageURL.TrimStart('/'));
                        ViewData["fileExist"] = System.IO.File.Exists(filePath);
                    }
                    else
                    {
                        ViewData["fileExist"] = false;
                    }
                    shoeEditVM = _mapper?.Map<ShoeEditVM>(shoe);
                    RercargarCombos(shoeEditVM);
                    shoeEditVM!.ReturnUrl = returnurl;

                    return View(shoeEditVM);
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return View(shoeEditVM);
        }
        private void RercargarCombos(ShoeEditVM? shoeEditVM)
        {
            shoeEditVM!.Brands = _brandService!.GetBrands()!
                .Select(b => new SelectListItem
                {
                    Text = b.BrandName,
                    Value = b.BrandId.ToString()
                }
                ).ToList();
            shoeEditVM.Colours = _colorService!.GetColours()!
              .Select(c => new SelectListItem
              {
                  Text = c.ColorName,
                  Value = c.ColourId.ToString()
              }
              ).ToList();
            shoeEditVM.Genres = _genreService!.GetGenres()!
              .Select(g => new SelectListItem
              {
                  Text = g.GenreName,
                  Value = g.GenreId.ToString()
              }
              ).ToList();
            shoeEditVM.Sports = _sportService!.GetSports()!
              .Select(s => new SelectListItem
              {
                  Text = s.SportName,
                  Value = s.SportId.ToString()
              }
              ).ToList();
        }
        [HttpPost]
        public IActionResult UpSert(ShoeEditVM shoeEditVM)
        {
            string? returnurl = shoeEditVM!.ReturnUrl;
            if (!ModelState.IsValid)
            {
                RercargarCombos(shoeEditVM);
                return View(shoeEditVM);
            }
            try
            {
                string? webroot = _webHostEnvironment!.WebRootPath;

TPN1EnWeb.Web/Areas/Admin/Controllers/SizeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using TPN1EnWeb.Entidades;
using TPN1EnWeb.Entidades.ViewModels;
using TPN1EnWeb.Servicios.Interfaces;
using TPN1EnWeb.Servicios.Servicios;
using X.PagedList.Extensions;
using Size = TPN1EnWeb.Entidades.Size;

namespace TPN1EnWeb.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SizeController : Controller
    {
        private readonly ISizeService? _sizeService;
        private readonly IMapper? _mapper;
        private readonly IShoeService? _shoeService;
        private readonly IShoeSizeService? _shoeSizeService;

        public SizeController(ISizeService? sizeService, IMapper? mapper, IShoeService? shoeService, IShoeSizeService? shoeSizeService)
        {
            _sizeService = sizeService;
            _mapper = mapper;
            _shoeService = shoeService;
            _shoeSizeService = shoeSizeService;
        }

        public IActionResult Index(int? page)
        {
            int pagenumber = page ?? 1;
            int pagesize = 7;
            var lista = _sizeService?.GetSizes().ToPagedList(pagenumber, pagesize);
            return View(lista);
        }
        public IActionResult Details(int id)
        {
            var size = _sizeService?.GetSize(filter: s => s.SizeId == id);
            var listashoe = _sizeService?.GetShoePorSize(size!);
            var listasizevm = new List<SizeShoeListVM>();
            foreach (var shoeVM in listashoe!)
            {
                var SIZEFORVIEW = new SizeShoeListVM()
                {
                    SizeId = size!.SizeId,
                    BrandName = shoeVM.brand!,
                    ColorName = shoeVM.color!,
                    GenreName = shoeVM.genre!,
                    SportName = shoeVM.sport!,
                    Model = shoeVM.model,
                    Description = shoeVM.descripcion,
                    Price = shoeVM.price.ToString(),
                    ShoeId = shoeVM.shoeId,
                    SizeNumber = size.SizeNumber,
                    Stock = _shoeSizeService!.GetIdShoeSize(size.SizeId, shoeVM.shoeId).QuantityInStock
                };
                listasizevm.Add(SIZEFORVIEW);
            }
            return View(listasizevm);
        }
        public IActionResult UpdateStock(int SizeId, int id)
        {
            var Size = _sizeService!.GetSizePorId(SizeId);
            var Shoe = _shoeService!.GetShoe(filter: shoe => shoe.ShoeId == id, propertiesNames: "Sports,Brands,Color,Genres");
            var shoeSize = _shoeSizeService!.GetIdShoeSize(SizeId, id);
            return View(shoeSize);
        }
        [HttpPost]
        public IActionResult UpdateStock(ShoeSizes shoeSize)
        {
            if (shoeSize.QuantityInStock == 0)
            {
                ModelState.AddModelError(string.Empty, "Record need to be positive");
                return View(shoeSize);
            }
            Size size = _sizeService!.GetSize(filter: filter => filter.SizeId == shoeSize.SizeId)!;
            var shoe = _shoeService?.GetShoe(s => s.ShoeId == shoeSize.ShoeId, propertiesNames: "Sports,Brands,Color,Genres");
            ShoeSizes shoeSizes = _shoeSizeService!.GetIdShoeSize(size.SizeId, shoe!.ShoeId);
            shoeSizes.QuantityInStock += shoeSize.QuantityInStock;
            if (shoeSizes.QuantityInStock < 0)
            {
                ModelState.AddModelError(string.Empty, "The record must to be Positive or equal to 0");
                return View(shoeSizes);
            }
            try
            {
                if (_shoeService!.ExisteRelacion(shoe, size))
                {
                    _shoeSizeService.Save(shoeSizes);
                    TempData["success"] = "Record successfully edited";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Record already exist");
                    return View(shoeSize);
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while editing the record.");
                return View(shoeSize);
            }
        }

        [HttpDelete]
        public IActionResult Delete(int? shoeId,int? sizeId)
        {
            if (sizeId == null || sizeId == 0 || shoeId == null || shoeId == 0)
            {
                return NotFound();
            }
            Shoe? shoe = _shoeService?.GetShoe(filter: g => g.ShoeId == shoeId);
            Size? size = _sizeService?.GetSize(filter: s => s.SizeId == sizeId);

            ShoeSizes shoeSizes = _shoeSizeService?.GetShoeSize(filter:sh=>sh.ShoeId==shoe!.ShoeId && sh.SizeId==size!.SizeId)!;

            if (shoeSizes==null)
            {
                return NotFound();
            }
            if (_shoeSizeService!.ItsRelated(shoeSizes))
            {
                return Json(new
                {
                    success = false,
                    message = "Related Record..."
                });
            }
            _shoeSizeService!.Delete(shoeSizes);
            return Json(new { success = true, message = "Record deleted successfully" });

        }

    }
}

TPN1EnWeb.Web/Areas/Customer/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TPN1EnWeb.Servicios.Interfaces;

namespace TPN1EnWeb.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = "Customer, Admin")]
    public class OrdersController : Controller
    {
        private readonly IOrderHeadersService? _headersService;
        private readonly IShoeSizeService _shoeSizeService;
        private readonly IMapper? _mapper;

        public OrdersController(IOrderHeadersService? headersService,
            IShoeSizeService shoeSizeService,
            IMapper? mapper)
        {
            _headersService = headersService;
            _shoeSizeService = shoeSizeService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var orderHeader = _headersService!.Get(filter: o => o.OrderHeaderId == id,
                propertiesNames: "OrderDetail");
            foreach (var detail in orderHeader!.OrderDetail)
            {
                var shoesizeInDetail = _shoeSizeService.GetShoeSize(filter: p => p.ShoeSizeId == detail.ShoeSizeId, propertiesNames:"Shoe,Size");
                detail.ShoeSizes = shoesizeInDetail;
            }
            return View(orderHeader);
        }
        #region API CALLS
        [HttpGet]
        public JsonResult GetAll() 
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity!;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var orderList = _headersService!.GetAll(filter:
                o => o.ApplicationUserId == claims!.Value);
            return Json(new { data = orderList });
        }
        #endregion
    }
}

TPN1EnWeb.Web/Views/Shared/_Layout.cshtml
@using TPN1EnWeb.Utilities
<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TPN1EnWeb.Web</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.tiny.cloud/1/wd9v0389nuw4oq9n8f1i2e0ies6urzfyt0ycipbzcjaq51g9/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TPN1EnWeb.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body style="background-color:#121212">
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background-color: #000000; ">
            <div class="container-fluid" >
                @if (User.IsInRole(WC.Role_Admin))
                {
                    <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index" style="color:white">Shoes Web</a>
                }
                else{
                    <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index" style="color:white">Shoes Web</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1" style="color:crimson">
                        @if (User.IsInRole(WC.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Brand" asp-action="Index" style="color:white">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Colour" asp-action="Index" style="color:white">Colours</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Genre" asp-action="Index" style="color:white">Genres</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Sport" asp-action="Index" style="color:white">Sports</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Shoe" asp-action="Index" style="color:white">Shoes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Size" asp-action="Index" style="color:white">Size</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="ApplicationUsers" asp-action="Index" style="color:white">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Countries" asp-action="Index" style="color:white">Countries</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="States" asp-action="Index" style="color:white">States</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Cities" asp-action="Index" style="color:white">Cities</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index" style="color:white">ViewOfCustomer </a>
                            </li>
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Customer" asp-action="Index" asp-controller="Orders" style="color:white">
                                    My Purchases
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="@Url.Action("Index","ShoppingCarts",new{returnUrl=Url.Action("Index","Home",new{page=ViewBag.currentPage})})" style="color:white">
                                    <i class="bi bi-cart4"></i>
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>  

    <footer class="footer text-muted">
        <div class="container" style="color:#ffffff">
            &copy; 2024 - Shoes.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js">
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script> @*Este es necesario para cambiar el formato de la fecha en el archivo order.js*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>@*Este es necesario para cambiar el formato del precio en el archivo order.js*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TPN1EnWeb.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    var msg = TempData["success"]?.ToString();
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    var msg = TempData["error"]?.ToString();
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

TPN1EnWeb.Web/Views/Shared/_Pager.cshtml
@using X.PagedList
@using X.Web.PagedList
@model IPagedList;

<div class="d-flex">
    @Html.PagedListPager(Model, page => Url.Action("Index", new
        {
            page,
            searchTerm = ViewBag.currentSearchTerm,
            pageSize = ViewBag.currentPageSize,
            FilterBrandId = ViewBag.currentFilterBrandId,
            FilterColorId = ViewBag.currentFilterColorId,
            FilterGenreId = ViewBag.currentFilterGenreId,
            FilterSportId = ViewBag.currentFilterSportId,
            orderBY=ViewBag.currentOrderBy
        }), new PagedListRenderOptions
{
    UlElementClasses = new[] { "pagination" },
    LiElementClasses = new[] { "page-item" },
    PageClasses = new[] { "page-link" },
    DisplayLinkToIndividualPages = true,
    DisplayPageCountAndCurrentLocation = false,
    MaximumPageNumbersToDisplay = 10
})
</div>

<style>

    .pagination {
        display: flex;
        list-style: none;
    }

    .page-link {
        color: white; /* Color del texto del enlace */
        background-color: #000000; /* Fondo del enlace */
        border: 1px solid #dee2e6;
    }

        .page-link:hover {
            color: #0056b3; /* Color del texto cuando el mouse pasa por encima */
            background-color: #e9ecef; /* Fondo cuando el mouse pasa por encima */
            border-color: #dee2e6;
        }
    /* Para el enlace activo */
    .page-item.active .page-link {
        color: white; /* color de numero*/
        background-color: #005f73; /* color de relleno de celda */
        border-color: #007bff; /* color de borde */
    }

</style>

TPN1EnWeb.Web/Views/Shared/_selectPageSize.cshtml
@{
    int optionselected = ViewBag.currentPageSize;
}
<select class="form-select" id="pageSize" name="pageSize" onchange="this.form.submit()" style="width:70px">
    @{
        var options = new List<int> { 5, 10, 15, 20 };
        foreach (var option in options)
        {
           <option selected="@(optionselected==option? "selected":null)" value="@option">@option</option>
        }
    }
</select>