TPN1EnWeb.Web/Areas/Admin/Controllers/SportController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TPN1EnWeb.Entidades.ViewModels;
using TPN1EnWeb.Entidades;
using TPN1EnWeb.Servicios.Interfaces;
using TPN1EnWeb.Servicios.Servicios;
using X.PagedList.Extensions;
using System.Drawing.Drawing2D;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace TPN1EnWeb.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SportController : Controller
    {
        private readonly ISportService? _sportService;
        private readonly IMapper? _mapper;
        private readonly IShoeService _shoeService;
        public SportController(ISportService? sportService, IMapper? mapper, IShoeService shoeService)
        {
            _sportService = sportService;
            _mapper = mapper;
            _shoeService = shoeService;
        }

        public IActionResult Index(int? page, string? searchTerm = null, int pageSize = 10, bool viewAll = false)
        {
            int pagenumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            ViewBag.currentsearchTerm = searchTerm; //Un viewBag es como una variable de la vista que se usa en la vista para no ensuciar más el modelo de mi vista
            IEnumerable<Sport> sports;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    sports = _sportService!.GetSports(orderBy: o => o.OrderBy(c => c.SportName), filter: f => f.SportName.Contains(searchTerm!))!;
                }
                else
                {
                    sports = _sportService!.GetSports(orderBy: o => o.OrderBy(b => b.SportName))!;
                }
            }
            else
            {
                searchTerm = string.Empty;
                ViewBag.currentsearchTerm = searchTerm;
                sports = _sportService!.GetSports(orderBy: o => o.OrderBy(b => b.SportName))!;

            }
            var listasportdvm = new List<SportListVM>();
            foreach (var sport in sports!)
            {
                var sportVm = new SportListVM()
                {
                    SportId = sport.SportId,
                    SportName = sport.SportName,
                    ShoeCount = _shoeService!.GetCantidad(s => s.SportId == sport.SportId)
                };
                listasportdvm.Add(sportVm);
            }
            PagedList<SportListVM> listaVm = new PagedList<SportListVM>(listasportdvm, pagenumber, pageSize);
            listaVm.ToPagedList(pagenumber, pageSize);
            return View(listaVm);
        }

        public IActionResult UpSert(int? id, string? returnurl = null)
        {
            SportEditVM? sportEditVM;
            if (id is null || id.Value == 0)
            {
                sportEditVM = new SportEditVM();
            }
            else
            {
                Sport? sport = _sportService?.GetSport(filter: s => s.SportId == id);
                if (sport == null)
                {
                    return NotFound();
                }
                sportEditVM = _mapper?.Map<SportEditVM>(sport);
                sportEditVM!.ReturnUrl = returnurl;
            }
            return View(sportEditVM);
        }
        [HttpPost]
        public IActionResult UpSert(SportEditVM? sportEditVM)
        {
            string? returnurl = sportEditVM!.ReturnUrl;
            if (!ModelState.IsValid)
            {
                return View(sportEditVM);
            }
            Sport? sport = _mapper?.Map<Sport>(sportEditVM);
            if (sport == null)
            {
                ModelState.AddModelError(string.Empty, "No Colour has been supplied");
                return View(sportEditVM);
            }
            if (_sportService?.Existe(sport) ?? true)
            {
                ModelState.AddModelError(string.Empty, "Registro Duplicado¡¡¡¡");
                return View(sportEditVM);
            }
            _sportService.Guardar(sport);
            TempData["success"] = "Record added/edited successfully";
            return !string.IsNullOrEmpty(returnurl)
            ? Redirect(returnurl)
            : RedirectToAction("Index");
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Sport? sport = _sportService?.GetSport(filter: s => s.SportId == id);
            if (sport == null)
            {
                return NotFound();
            }
            if (_sportService?.EstaRelacionado(sport) ?? true)
            {
                return Json(new
                {
                    success = false,
                    message = "Related Record..."
                });
            }
            _sportService?.Borrar(sport);
            return Json(new { success = true, message = "Record deleted successfully" });

        }
        public IActionResult Details(int? id)
        {
            Sport Sport = _sportService?.GetSport(filter: filter => filter.SportId == id)!;
            if (Sport is null)
            {
                return NotFound();
            }
            IEnumerable<Shoe> listaShoeFiltradaPorBrand;
            listaShoeFiltradaPorBrand = _shoeService?.GetShoes(filter: filter => filter.SportId == id, propertiesNames: "Genres,Color,Sports,Brands")!;
            var listavm = _mapper?.Map<IEnumerable<ShoeListVM>>(listaShoeFiltradaPorBrand).ToList();
            return View(listavm);
        }
    }
}

TPN1EnWeb.Web/Areas/Admin/Views/Sport/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Sport
@{
    ViewData["Title"] = "Delete Sport";
}
<form method="post" asp-controller="Sport" asp-action="Delete">
    @*CUANDO COPIES Y PEGUES ACORDATE DE CAMBIAR LAS ACCIONES Y LOS CONTROLADORES*@
    <input type="hidden" asp-for="SportId" />@*IMPORTANTE ESTE CAMPO CUANDO EDITO O BORRO
    ya que acá se guarda el ID de mi objeto, si yo no pongo este campo en vez de editar va a guardar en este caso o en vez de borrar
    lo que va a pasar es que no pueda encontrar el objeto porque el ID va a ser 0
    *@

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Delete Sport</h2>
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="SportName"></label>@*Esto es como el titulo de nuestro input para agregar datos*@
        <input asp-for="SportName" disabled type="text" class="form-control" />@*Esto es para ingresar el Colour nuevo*@
    </div>
    <button class="btn btn-danger">
        <i class="bi bi-save"></i>
        Confirm
    </button>
    <a asp-controller="Sport" asp-action="Index" class="btn btn-info">
        @*Conesto indico con que controlador manejar y que acción realizar
        en este caso es regresar a la lista*@
        <i class="bi bi-arrow-return-left"></i>
        Back to List
    </a>
</form>

TPN1EnWeb.Web/Areas/Admin/Views/Sport/Details.cshtml
@model IEnumerable<ShoeListVM>
@{
    ViewData["Title"] = "List of Shoes";
}
<div class="row w-60 mb-3">
    <div class="col-8">
        <h1 style="color:white">
            Shoes with this Sport:@{
                foreach (var item in Model)
                {
                    @item.sport
                    break;
                }
            }
        </h1>
    </div>
</div>
<table class="table table-dark table-hover w-auto  ">
    <thead class="border-2">
        <tr bordercolor="dark">
            <th colspan="8" valign="middle" align="center">Shoe</th>
        </tr>
        <tr>
            <th>Brand</th>
            <th>Color</th>
            <th>Genre</th>
            <th>Model</th>
            <th>Price</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr id="@item.shoeId">
                    <td>@Html.Raw(@item.brand)</td>
                    <td>@Html.Raw(@item.color)</td>
                    <td>@Html.Raw(@item.genre)</td>
                    <td>@Html.Raw(@item.model)</td>
                    <td>@Html.Raw(@item.price)</td>
                    <td>@Html.Raw(@item.descripcion)</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>No hay datos en la lista</td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="Sport" asp-action="Index" class="btn btn-info">
    <i class="bi bi-arrow-return-left"></i>
    Back to List
</a>

TPN1EnWeb.Web/Areas/Admin/Views/Sport/Index.cshtml
@using X.PagedList
@using X.Web.PagedList
@model IPagedList<SportListVM>;

@{
    ViewData["Title"] = "List of Sport";//Esto es como un <h2>???
}

<div class="row w-60 mb-3">
    <div class="col-5">
        <h1 style="color:white">List of Sport</h1>
    </div>
</div>
<form method="get" class="form-inline" asp-action="Index" style="padding-bottom:5px">
    <div class="d-flex flex-row align-items-center">
        <div class="col-auto mx-1">
            <label for="pageSize" style="color:white">Show:</label>
        </div>
        <div class="col-auto mx-2">
            <partial name="_selectPageSize" model="ViewBag.currentPageSize" />
        </div>
        <div class="col-auto mx-2" style="width: 200px;">
            <input type="text" name="searchTerm" id="searchTerm" class="form-control" placeholder="Search by..." value="@ViewBag.currentSearchTerm" />
        </div>
        <div class="col-auto d-flex">
            <button type="submit" class="btn btn-primary mx-2">
                <i class="bi bi-search"></i> Search
            </button>
            <button type="submit" class="btn btn-secondary" id="viewAll" name="viewAll" value="true">
                <i class="bi bi-list"></i> View All
            </button>
        </div>
        <div class="col-7 mx-2">
            <a asp-controller="Sport" asp-action="UpSert" class="btn btn-dark">
                <i class="bi bi-node-plus-fill"></i>
                New
            </a>
        </div>
    </div>
</form>

<table class="table table-dark table-hover w-75">
    <thead>
        <tr>
            <th>Sport Name</th>
            <td>Countity of Shoes by Sport</td>
            <th>Accions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <tr id="@item.SportId">
                    <td>
                        @Html.Raw(@item.SportName)@*Este HTML.RAW permite mostrar el texto como se Modifico en el textarea,
                esto quiere decir que puede ser texto en negrita, cursiva, etc*@
                    </td>
                    <td class="text-aling text-center">@item.ShoeCount</td>
                    <td>
                        <a onclick="Delete('/Admin/Sport/Delete/@item.SportId', @item.SportId,'@item.SportName')" class="btn btn-danger">
                            <i class="bi bi-trash"></i>
                            Delete
                        </a>
                        @*El nombre "id" del asp-route debe conicidirme con el que le paso en la acción Edit en el controlador*@
                        <a asp-controller="Sport" asp-action="UpSert" asp-route-id="@item.SportId" asp-route-returnurl="@(Context.Request.Path+Context.Request.QueryString)" class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                            Edit
                        </a>
                        <a asp-controller="Sport" asp-action="Details" asp-route-id="@item.SportId" class="btn btn-info" style="background-color:chartreuse">
                            Details
                        </a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>No hay datos en la lista</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>
<partial name="_Pager" model="@Model" />
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/common.js"></script>
}

TPN1EnWeb.Web/Areas/Admin/Views/Sport/UpSert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SportEditVM
@{
    ViewData["Title"] = "Add/Edit Sport";
}
<form method="post" asp-controller="Sport" asp-action="UpSert">
    <input type="hidden" asp-for="SportId" />
    <input type="hidden" asp-for="ReturnUrl" />

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> @(Model.SportId == 0 ? "Add Sport" : "Edit Sport")</h2>
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div> @*Este span es para que me muestre el mensaje de "registro duplicado"*@
    </div>
    <div class="mb-3">
        <label asp-for="SportName"></label>@*Esto es como el titulo de nuestro input para agregar datos*@
        <input asp-for="SportName" class="form-control" />@*Esto es para ingresar el Colour nuevo*@
        <span asp-validation-for="SportName" class="text-danger"></span> @*Este span es para que me muestre el mensaje de "Debe ingresar un registro"*@
    </div>
    @if (Model.SportId == 0)
    {
        <button type="submit" class="btn btn-success">
            <i class="bi bi-save"></i>
            Confirm
        </button>
    }
    else
    {
        <button type="submit" class="btn btn-warning">
            <i class="bi bi-save"></i>
            Confirm
        </button>
    }

    <a asp-controller="Sport" asp-action="Index" class="btn btn-info">
        @*Con esto indico con que controlador manejar y que acción realizar
        en este caso es regresar a la lista*@
        <i class="bi bi-arrow-return-left"></i>
        Back to List
    </a>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}